// Generated by https://quicktype.io

export interface PagedResult {
    page: number;
    pageSize: number;
    collection: Ticket[];
    count: number;
}

export interface Ticket {
    creatoIl: string;
    _id: string;
    titolo: string;
    _cliente: string;
    _tecnico: string;
    eventi: Evento[];
    __v: number;
}

export interface Evento {
    creatoIl: string;
    _id: string;
    testo: string;
    creatoDa: string;
    file: string;
}